config/routes.rb
Vozdopovo::Application.routes.draw do
  resources :ouves

  resources :tags

  resources :ministerios

  resources :municipios

  get "home/index"

  match '/auth/facebook/callback' => 'services#create' 
  resources :services, :only => [:index, :create]

   root :to => "home#index"

end

app/models/municipio.rb
class Municipio < ActiveRecord::Base
end

app/controllers/municipios_controller.rb
class MunicipiosController < ApplicationController
  # GET /municipios
  # GET /municipios.xml
  def index
    @municipios = Municipio.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @municipios }
    end
  end

  # GET /municipios/1
  # GET /municipios/1.xml
  def show
    @municipio = Municipio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @municipio }
    end
  end

  # GET /municipios/new
  # GET /municipios/new.xml
  def new
    @municipio = Municipio.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @municipio }
    end
  end

  # GET /municipios/1/edit
  def edit
    @municipio = Municipio.find(params[:id])
  end

  # POST /municipios
  # POST /municipios.xml
  def create
    @municipio = Municipio.new(params[:municipio])

    respond_to do |format|
      if @municipio.save
        format.html { redirect_to(@municipio, :notice => 'Municipio was successfully created.') }
        format.xml  { render :xml => @municipio, :status => :created, :location => @municipio }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @municipio.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /municipios/1
  # PUT /municipios/1.xml
  def update
    @municipio = Municipio.find(params[:id])

    respond_to do |format|
      if @municipio.update_attributes(params[:municipio])
        format.html { redirect_to(@municipio, :notice => 'Municipio was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @municipio.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /municipios/1
  # DELETE /municipios/1.xml
  def destroy
    @municipio = Municipio.find(params[:id])
    @municipio.destroy

    respond_to do |format|
      format.html { redirect_to(municipios_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/municipios_helper.rb
module MunicipiosHelper
end

app/views/municipios/_form.html.erb
<%= form_for(@municipio) do |f| %>
  <% if @municipio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@municipio.errors.count, "error") %> prohibited this municipio from being saved:</h2>

      <ul>
      <% @municipio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :coordenadas %><br />
    <%= f.text_field :coordenadas %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/municipios/edit.html.erb
<h1>Editing municipio</h1>

<%= render 'form' %>

<%= link_to 'Show', @municipio %> |
<%= link_to 'Back', municipios_path %>

app/views/municipios/index.html.erb
<h1>Listing municipios</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Coordenadas</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @municipios.each do |municipio| %>
  <tr>
    <td><%= municipio.nome %></td>
    <td><%= municipio.coordenadas %></td>
    <td><%= link_to 'Show', municipio %></td>
    <td><%= link_to 'Edit', edit_municipio_path(municipio) %></td>
    <td><%= link_to 'Destroy', municipio, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Municipio', new_municipio_path %>

app/views/municipios/new.html.erb
<h1>New municipio</h1>

<%= render 'form' %>

<%= link_to 'Back', municipios_path %>

app/views/municipios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @municipio.nome %>
</p>

<p>
  <b>Coordenadas:</b>
  <%= @municipio.coordenadas %>
</p>


<%= link_to 'Edit', edit_municipio_path(@municipio) %> |
<%= link_to 'Back', municipios_path %>