config/routes.rb
Vozdopovo::Application.routes.draw do
  resources :ouves

  resources :tags

  resources :ministerios

  resources :municipios

  get "home/index"

  match '/auth/facebook/callback' => 'services#create' 
  resources :services, :only => [:index, :create]

   root :to => "home#index"

end

app/models/ministerio.rb
class Ministerio < ActiveRecord::Base
end

app/controllers/ministerios_controller.rb
class MinisteriosController < ApplicationController
  # GET /ministerios
  # GET /ministerios.xml
  def index
    @ministerios = Ministerio.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @ministerios }
    end
  end

  # GET /ministerios/1
  # GET /ministerios/1.xml
  def show
    @ministerio = Ministerio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @ministerio }
    end
  end

  # GET /ministerios/new
  # GET /ministerios/new.xml
  def new
    @ministerio = Ministerio.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @ministerio }
    end
  end

  # GET /ministerios/1/edit
  def edit
    @ministerio = Ministerio.find(params[:id])
  end

  # POST /ministerios
  # POST /ministerios.xml
  def create
    @ministerio = Ministerio.new(params[:ministerio])

    respond_to do |format|
      if @ministerio.save
        format.html { redirect_to(@ministerio, :notice => 'Ministerio was successfully created.') }
        format.xml  { render :xml => @ministerio, :status => :created, :location => @ministerio }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @ministerio.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ministerios/1
  # PUT /ministerios/1.xml
  def update
    @ministerio = Ministerio.find(params[:id])

    respond_to do |format|
      if @ministerio.update_attributes(params[:ministerio])
        format.html { redirect_to(@ministerio, :notice => 'Ministerio was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @ministerio.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ministerios/1
  # DELETE /ministerios/1.xml
  def destroy
    @ministerio = Ministerio.find(params[:id])
    @ministerio.destroy

    respond_to do |format|
      format.html { redirect_to(ministerios_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/ministerios_helper.rb
module MinisteriosHelper
end

app/views/ministerios/_form.html.erb
<%= form_for(@ministerio) do |f| %>
  <% if @ministerio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ministerio.errors.count, "error") %> prohibited this ministerio from being saved:</h2>

      <ul>
      <% @ministerio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ministerios/edit.html.erb
<h1>Editing ministerio</h1>

<%= render 'form' %>

<%= link_to 'Show', @ministerio %> |
<%= link_to 'Back', ministerios_path %>

app/views/ministerios/index.html.erb
<h1>Listing ministerios</h1>

<table>
  <tr>
    <th>Nome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ministerios.each do |ministerio| %>
  <tr>
    <td><%= ministerio.nome %></td>
    <td><%= link_to 'Show', ministerio %></td>
    <td><%= link_to 'Edit', edit_ministerio_path(ministerio) %></td>
    <td><%= link_to 'Destroy', ministerio, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ministerio', new_ministerio_path %>

app/views/ministerios/new.html.erb
<h1>New ministerio</h1>

<%= render 'form' %>

<%= link_to 'Back', ministerios_path %>

app/views/ministerios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @ministerio.nome %>
</p>


<%= link_to 'Edit', edit_ministerio_path(@ministerio) %> |
<%= link_to 'Back', ministerios_path %>