config/routes.rb
Vozdopovo::Application.routes.draw do
  resources :ouves

  resources :tags

  resources :ministerios

  resources :municipios

  get "home/index"

  match '/auth/facebook/callback' => 'services#create' 
  resources :services, :only => [:index, :create]

   root :to => "home#index"

end

app/models/ouve.rb
class Ouve < ActiveRecord::Base
  belongs_to :municipio
  belongs_to :ministerio
end

app/controllers/ouves_controller.rb
class OuvesController < ApplicationController
  # GET /ouves
  # GET /ouves.xml
  def index
    @ouves = Ouve.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @ouves }
    end
  end

  # GET /ouves/1
  # GET /ouves/1.xml
  def show
    @ouve = Ouve.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @ouve }
    end
  end

  # GET /ouves/new
  # GET /ouves/new.xml
  def new
    @ouve = Ouve.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @ouve }
    end
  end

  def new_main
   @ouve.titulo = params[:titulo] 
  end

  # GET /ouves/1/edit
  def edit
    @ouve = Ouve.find(params[:id])
  end

  # POST /ouves
  # POST /ouves.xml
  def create
    @ouve = Ouve.new(params[:ouve])

    respond_to do |format|
      if @ouve.save
        format.html { redirect_to(@ouve, :notice => 'Ouve was successfully created.') }
        format.xml  { render :xml => @ouve, :status => :created, :location => @ouve }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @ouve.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ouves/1
  # PUT /ouves/1.xml
  def update
    @ouve = Ouve.find(params[:id])

    respond_to do |format|
      if @ouve.update_attributes(params[:ouve])
        format.html { redirect_to(@ouve, :notice => 'Ouve was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @ouve.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ouves/1
  # DELETE /ouves/1.xml
  def destroy
    @ouve = Ouve.find(params[:id])
    @ouve.destroy

    respond_to do |format|
      format.html { redirect_to(ouves_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/ouves_helper.rb
module OuvesHelper
end

app/views/ouves/_form.html.erb
<%= form_for(@ouve) do |f| %>
  <% if @ouve.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ouve.errors.count, "error") %> prohibited this ouve from being saved:</h2>

      <ul>
      <% @ouve.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :ideia %><br />
    <%= f.text_area :ideia %>
  </div>
  <div class="field">
    <%= f.label :municipio %><br />
    <%= f.collection_select( :municipio_id , Municipio.all, :id, :nome, {:include_blank => true}) %>
  </div>
  <div class="field">
    <%= f.label :ministerio %><br />
    <%= f.collection_select( :ministerio_id, Ministerio.all, :id, :nome, {:include_blank => true}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ouves/edit.html.erb
<h1>Editing ouve</h1>

<%= render 'form' %>

<%= link_to 'Show', @ouve %> |
<%= link_to 'Back', ouves_path %>

app/views/ouves/index.html.erb
<h1>Listing ouves</h1>

<table>
  <tr>
    <th>Titulo</th>
    <th>Ideia</th>
    <th>Municipio</th>
    <th>Ministerio</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ouves.each do |ouve| %>
  <tr>
    <td><%= ouve.titulo %></td>
    <td><%= ouve.ideia %></td>
    <td><%= ouve.municipio %></td>
    <td><%= ouve.ministerio %></td>
    <td><%= link_to 'Show', ouve %></td>
    <td><%= link_to 'Edit', edit_oufe_path(ouve) %></td>
    <td><%= link_to 'Destroy', ouve, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ouve', new_oufe_path %>

app/views/ouves/new.html.erb
<h1>New ouve</h1>

<%= render 'form' %>

<%= link_to 'Back', ouves_path %>

app/views/ouves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @ouve.titulo %>
</p>

<p>
  <b>Ideia:</b>
  <%= @ouve.ideia %>
</p>

<p>
  <b>Municipio:</b>
  <%= @ouve.municipio.nome %>
</p>

<p>
  <b>Ministerio:</b>
  <%= @ouve.ministerio.nome %>
</p>


<%= link_to 'Edit', edit_oufe_path(@ouve) %> |
<%= link_to 'Back', ouves_path %>